# Site settings
title: Random() Ramblings
author:
	name: Vijesh Mohan
	email: mv.vijesh@gmail.com
	github: vijeshm
	twitter: edbidangi
email: mv.vijesh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just some random ramblings.. here and there, every now and then.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://vijesh.me" # the base hostname & protocol for your site
twitter_username: edbidangi
github_username:  vijeshm

# Build settings
markdown: kramdown
